networks:
  back:
    name: backnet
    external: true
  app:
    name: appnet
    external: true

services:
  back:
    container_name: django-fastapi
    env_file: ./back/.env
    ports:
      - 8000:8000
    networks:
      - back
      - app

  db:
    image: postgres:17.0-alpine3.20
    env_file: .env
    networks:
      - back

  cache:
    image: redis:7.4.1-alpine3.20
    networks:
      - back