networks:
  back:
    name: back-dev
    
  app:
    name: app-dev

services:
  front:
    image: node:20-slim
    command: ["sh", "-c", "cd /app && npm install && npm run dev -- --host"]
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 3000:5173
    networks:
      - app

  back:
    environment:
      - ENV=development
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back:/app
      - /app/static/admin/
  
  db:
    volumes:
      - ./pgdata:${PGDATA}

  cache: 
    volumes:
      - ./redis:/data

  sonar:
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data 
      - ./sonarqube/extensions:/opt/sonarqube/extensions 
      - ./sonarqube/logs:/opt/sonarqube/logs