services:
  back:
    environment:
      - ENV=development
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back/api:/app/api
      - ./back/core:/app/core
  
  db:
    volumes:
      - ./pgdata:${PGDATA}

  cache: 
    volumes:
      - ./redis:/data

  front:
    image: node:20-slim
    command: ["sh", "-c", "cd /app && npm install && npm run dev -- --host"]
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 3000:5173
    networks:
      - app
    depends_on:
      back:
        condition: service_healthy