FROM python:3.12.7-slim 
WORKDIR /app

RUN apt update && apt install -y lsof && pip install poetry

COPY . .

RUN poetry install

ENTRYPOINT ["sh", "-c", "poetry run python3 manage.py collectstatic -l --noinput && exec poetry run uvicorn core.asgi:app --host 0.0.0.0 --reload"]
